# Docker Compose Override for Development Environment
# 이 파일은 개발 환경에서 docker-compose.yaml과 자동으로 병합됩니다.
# 용도: 개발환경에서 리소스 제한을 완화하고 디버깅을 위한 설정 추가

services:
  # 개발환경에서는 리소스 제한을 더 관대하게 설정
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # 개발환경에서는 Redis 포트를 외부에 노출
    ports:
      - "6379:6379"

  db:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 128M
    # 개발환경에서는 PostgreSQL 포트를 외부에 노출
    ports:
      - "5432:5432"

  fastify-member-server:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M
    # 개발환경에서는 포트를 외부에 노출
    ports:
      - "5000:5000"
    # 소스코드 볼륨 마운트 (핫 리로드)
    volumes:
      - ./fastify-member-server/src:/app/src:ro
    # 개발 모드로 실행
    environment:
      - NODE_ENV=development

  koa-auth-server:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    # 개발환경에서는 포트를 외부에 노출
    ports:
      - "4000:4000"
    # 소스코드 볼륨 마운트 (핫 리로드)
    volumes:
      - ./koa-auth-server/src:/app/src:ro
    # 개발 모드로 실행
    environment:
      - NODE_ENV=development

  bff-server:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    # 개발환경에서는 포트를 외부에 노출
    ports:
      - "8000:8000"
    # 소스코드 볼륨 마운트 (핫 리로드)
    volumes:
      - ./bff-server/src:/app/src:ro
    # 개발 모드로 실행
    environment:
      - NODE_ENV=development

  proxy-server:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    # 소스코드 볼륨 마운트 (핫 리로드)
    volumes:
      - ./proxy-server/src:/app/src:ro
    # 개발 모드로 실행
    environment:
      - NODE_ENV=development

  ecommerce-app:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M
    # 소스코드 볼륨 마운트 (핫 리로드)
    volumes:
      - ./ecommerce-app/src:/app/src:ro
      - ./ecommerce-app/public:/app/public:ro
    # 개발 모드로 실행
    environment:
      - NODE_ENV=development

  kong:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 128M
    # 개발환경에서는 Kong Admin API 포트를 외부에 노출
    # ports:
    #   - "8001:8001"  # Kong Admin API
    #   - "8000:8000"  # Kong Proxy
# docker-compose up --build
