"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Product = void 0;
var typeorm_1 = require("typeorm");
var category_entity_1 = require("./category.entity");
var product_option_entity_1 = require("./product-option.entity");
var product_image_entity_1 = require("./product-image.entity");
var Product = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('products'), (0, typeorm_1.Index)(['categoryId', 'isActive']), (0, typeorm_1.Index)(['sellerId', 'isActive']), (0, typeorm_1.Index)(['createdAt'])];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _name_decorators;
    var _name_initializers = [];
    var _name_extraInitializers = [];
    var _description_decorators;
    var _description_initializers = [];
    var _description_extraInitializers = [];
    var _price_decorators;
    var _price_initializers = [];
    var _price_extraInitializers = [];
    var _originalPrice_decorators;
    var _originalPrice_initializers = [];
    var _originalPrice_extraInitializers = [];
    var _categoryId_decorators;
    var _categoryId_initializers = [];
    var _categoryId_extraInitializers = [];
    var _sellerId_decorators;
    var _sellerId_initializers = [];
    var _sellerId_extraInitializers = [];
    var _mainImage_decorators;
    var _mainImage_initializers = [];
    var _mainImage_extraInitializers = [];
    var _rating_decorators;
    var _rating_initializers = [];
    var _rating_extraInitializers = [];
    var _averageRating_decorators;
    var _averageRating_initializers = [];
    var _averageRating_extraInitializers = [];
    var _reviewCount_decorators;
    var _reviewCount_initializers = [];
    var _reviewCount_extraInitializers = [];
    var _isNew_decorators;
    var _isNew_initializers = [];
    var _isNew_extraInitializers = [];
    var _isFeatured_decorators;
    var _isFeatured_initializers = [];
    var _isFeatured_extraInitializers = [];
    var _isActive_decorators;
    var _isActive_initializers = [];
    var _isActive_extraInitializers = [];
    var _discountPercentage_decorators;
    var _discountPercentage_initializers = [];
    var _discountPercentage_extraInitializers = [];
    var _stock_decorators;
    var _stock_initializers = [];
    var _stock_extraInitializers = [];
    var _sku_decorators;
    var _sku_initializers = [];
    var _sku_extraInitializers = [];
    var _weight_decorators;
    var _weight_initializers = [];
    var _weight_extraInitializers = [];
    var _dimensions_decorators;
    var _dimensions_initializers = [];
    var _dimensions_extraInitializers = [];
    var _specifications_decorators;
    var _specifications_initializers = [];
    var _specifications_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _category_decorators;
    var _category_initializers = [];
    var _category_extraInitializers = [];
    var _options_decorators;
    var _options_initializers = [];
    var _options_extraInitializers = [];
    var _images_decorators;
    var _images_initializers = [];
    var _images_extraInitializers = [];
    var Product = _classThis = /** @class */ (function () {
        function Product_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.name = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _name_initializers, void 0));
            this.description = (__runInitializers(this, _name_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.price = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _price_initializers, void 0));
            this.originalPrice = (__runInitializers(this, _price_extraInitializers), __runInitializers(this, _originalPrice_initializers, void 0));
            this.categoryId = (__runInitializers(this, _originalPrice_extraInitializers), __runInitializers(this, _categoryId_initializers, void 0));
            this.sellerId = (__runInitializers(this, _categoryId_extraInitializers), __runInitializers(this, _sellerId_initializers, void 0));
            this.mainImage = (__runInitializers(this, _sellerId_extraInitializers), __runInitializers(this, _mainImage_initializers, void 0));
            this.rating = (__runInitializers(this, _mainImage_extraInitializers), __runInitializers(this, _rating_initializers, void 0));
            this.averageRating = (__runInitializers(this, _rating_extraInitializers), __runInitializers(this, _averageRating_initializers, void 0));
            this.reviewCount = (__runInitializers(this, _averageRating_extraInitializers), __runInitializers(this, _reviewCount_initializers, void 0));
            this.isNew = (__runInitializers(this, _reviewCount_extraInitializers), __runInitializers(this, _isNew_initializers, void 0));
            this.isFeatured = (__runInitializers(this, _isNew_extraInitializers), __runInitializers(this, _isFeatured_initializers, void 0));
            this.isActive = (__runInitializers(this, _isFeatured_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.discountPercentage = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _discountPercentage_initializers, void 0));
            this.stock = (__runInitializers(this, _discountPercentage_extraInitializers), __runInitializers(this, _stock_initializers, void 0));
            this.sku = (__runInitializers(this, _stock_extraInitializers), __runInitializers(this, _sku_initializers, void 0));
            this.weight = (__runInitializers(this, _sku_extraInitializers), __runInitializers(this, _weight_initializers, void 0));
            this.dimensions = (__runInitializers(this, _weight_extraInitializers), __runInitializers(this, _dimensions_initializers, void 0));
            this.specifications = (__runInitializers(this, _dimensions_extraInitializers), __runInitializers(this, _specifications_initializers, void 0));
            this.createdAt = (__runInitializers(this, _specifications_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            this.category = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _category_initializers, void 0));
            this.options = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _options_initializers, void 0));
            this.images = (__runInitializers(this, _options_extraInitializers), __runInitializers(this, _images_initializers, void 0));
            __runInitializers(this, _images_extraInitializers);
        }
        return Product_1;
    }());
    __setFunctionName(_classThis, "Product");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)()];
        _name_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 200 })];
        _description_decorators = [(0, typeorm_1.Column)({ type: 'text' })];
        _price_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 10, scale: 2 })];
        _originalPrice_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 10, scale: 2 })];
        _categoryId_decorators = [(0, typeorm_1.Column)({ type: 'int' })];
        _sellerId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 })];
        _mainImage_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 500, nullable: true })];
        _rating_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 3, scale: 2, default: 0 })];
        _averageRating_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 3, scale: 2, default: 0 })];
        _reviewCount_decorators = [(0, typeorm_1.Column)({ type: 'int', default: 0 })];
        _isNew_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _isFeatured_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _isActive_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: true })];
        _discountPercentage_decorators = [(0, typeorm_1.Column)({ type: 'int', default: 0 })];
        _stock_decorators = [(0, typeorm_1.Column)({ type: 'int', default: 0 })];
        _sku_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100, nullable: true })];
        _weight_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 8, scale: 2, nullable: true })];
        _dimensions_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _specifications_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _category_decorators = [(0, typeorm_1.ManyToOne)(function () { return category_entity_1.Category; }, function (category) { return category.products; }), (0, typeorm_1.JoinColumn)({ name: 'categoryId' })];
        _options_decorators = [(0, typeorm_1.OneToMany)(function () { return product_option_entity_1.ProductOption; }, function (option) { return option.product; }, {
                cascade: true,
            })];
        _images_decorators = [(0, typeorm_1.OneToMany)(function () { return product_image_entity_1.ProductImage; }, function (image) { return image.product; }, {
                cascade: true,
            })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _name_decorators, { kind: "field", name: "name", static: false, private: false, access: { has: function (obj) { return "name" in obj; }, get: function (obj) { return obj.name; }, set: function (obj, value) { obj.name = value; } }, metadata: _metadata }, _name_initializers, _name_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: function (obj) { return "description" in obj; }, get: function (obj) { return obj.description; }, set: function (obj, value) { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _price_decorators, { kind: "field", name: "price", static: false, private: false, access: { has: function (obj) { return "price" in obj; }, get: function (obj) { return obj.price; }, set: function (obj, value) { obj.price = value; } }, metadata: _metadata }, _price_initializers, _price_extraInitializers);
        __esDecorate(null, null, _originalPrice_decorators, { kind: "field", name: "originalPrice", static: false, private: false, access: { has: function (obj) { return "originalPrice" in obj; }, get: function (obj) { return obj.originalPrice; }, set: function (obj, value) { obj.originalPrice = value; } }, metadata: _metadata }, _originalPrice_initializers, _originalPrice_extraInitializers);
        __esDecorate(null, null, _categoryId_decorators, { kind: "field", name: "categoryId", static: false, private: false, access: { has: function (obj) { return "categoryId" in obj; }, get: function (obj) { return obj.categoryId; }, set: function (obj, value) { obj.categoryId = value; } }, metadata: _metadata }, _categoryId_initializers, _categoryId_extraInitializers);
        __esDecorate(null, null, _sellerId_decorators, { kind: "field", name: "sellerId", static: false, private: false, access: { has: function (obj) { return "sellerId" in obj; }, get: function (obj) { return obj.sellerId; }, set: function (obj, value) { obj.sellerId = value; } }, metadata: _metadata }, _sellerId_initializers, _sellerId_extraInitializers);
        __esDecorate(null, null, _mainImage_decorators, { kind: "field", name: "mainImage", static: false, private: false, access: { has: function (obj) { return "mainImage" in obj; }, get: function (obj) { return obj.mainImage; }, set: function (obj, value) { obj.mainImage = value; } }, metadata: _metadata }, _mainImage_initializers, _mainImage_extraInitializers);
        __esDecorate(null, null, _rating_decorators, { kind: "field", name: "rating", static: false, private: false, access: { has: function (obj) { return "rating" in obj; }, get: function (obj) { return obj.rating; }, set: function (obj, value) { obj.rating = value; } }, metadata: _metadata }, _rating_initializers, _rating_extraInitializers);
        __esDecorate(null, null, _averageRating_decorators, { kind: "field", name: "averageRating", static: false, private: false, access: { has: function (obj) { return "averageRating" in obj; }, get: function (obj) { return obj.averageRating; }, set: function (obj, value) { obj.averageRating = value; } }, metadata: _metadata }, _averageRating_initializers, _averageRating_extraInitializers);
        __esDecorate(null, null, _reviewCount_decorators, { kind: "field", name: "reviewCount", static: false, private: false, access: { has: function (obj) { return "reviewCount" in obj; }, get: function (obj) { return obj.reviewCount; }, set: function (obj, value) { obj.reviewCount = value; } }, metadata: _metadata }, _reviewCount_initializers, _reviewCount_extraInitializers);
        __esDecorate(null, null, _isNew_decorators, { kind: "field", name: "isNew", static: false, private: false, access: { has: function (obj) { return "isNew" in obj; }, get: function (obj) { return obj.isNew; }, set: function (obj, value) { obj.isNew = value; } }, metadata: _metadata }, _isNew_initializers, _isNew_extraInitializers);
        __esDecorate(null, null, _isFeatured_decorators, { kind: "field", name: "isFeatured", static: false, private: false, access: { has: function (obj) { return "isFeatured" in obj; }, get: function (obj) { return obj.isFeatured; }, set: function (obj, value) { obj.isFeatured = value; } }, metadata: _metadata }, _isFeatured_initializers, _isFeatured_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: function (obj) { return "isActive" in obj; }, get: function (obj) { return obj.isActive; }, set: function (obj, value) { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _discountPercentage_decorators, { kind: "field", name: "discountPercentage", static: false, private: false, access: { has: function (obj) { return "discountPercentage" in obj; }, get: function (obj) { return obj.discountPercentage; }, set: function (obj, value) { obj.discountPercentage = value; } }, metadata: _metadata }, _discountPercentage_initializers, _discountPercentage_extraInitializers);
        __esDecorate(null, null, _stock_decorators, { kind: "field", name: "stock", static: false, private: false, access: { has: function (obj) { return "stock" in obj; }, get: function (obj) { return obj.stock; }, set: function (obj, value) { obj.stock = value; } }, metadata: _metadata }, _stock_initializers, _stock_extraInitializers);
        __esDecorate(null, null, _sku_decorators, { kind: "field", name: "sku", static: false, private: false, access: { has: function (obj) { return "sku" in obj; }, get: function (obj) { return obj.sku; }, set: function (obj, value) { obj.sku = value; } }, metadata: _metadata }, _sku_initializers, _sku_extraInitializers);
        __esDecorate(null, null, _weight_decorators, { kind: "field", name: "weight", static: false, private: false, access: { has: function (obj) { return "weight" in obj; }, get: function (obj) { return obj.weight; }, set: function (obj, value) { obj.weight = value; } }, metadata: _metadata }, _weight_initializers, _weight_extraInitializers);
        __esDecorate(null, null, _dimensions_decorators, { kind: "field", name: "dimensions", static: false, private: false, access: { has: function (obj) { return "dimensions" in obj; }, get: function (obj) { return obj.dimensions; }, set: function (obj, value) { obj.dimensions = value; } }, metadata: _metadata }, _dimensions_initializers, _dimensions_extraInitializers);
        __esDecorate(null, null, _specifications_decorators, { kind: "field", name: "specifications", static: false, private: false, access: { has: function (obj) { return "specifications" in obj; }, get: function (obj) { return obj.specifications; }, set: function (obj, value) { obj.specifications = value; } }, metadata: _metadata }, _specifications_initializers, _specifications_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: function (obj) { return "category" in obj; }, get: function (obj) { return obj.category; }, set: function (obj, value) { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
        __esDecorate(null, null, _options_decorators, { kind: "field", name: "options", static: false, private: false, access: { has: function (obj) { return "options" in obj; }, get: function (obj) { return obj.options; }, set: function (obj, value) { obj.options = value; } }, metadata: _metadata }, _options_initializers, _options_extraInitializers);
        __esDecorate(null, null, _images_decorators, { kind: "field", name: "images", static: false, private: false, access: { has: function (obj) { return "images" in obj; }, get: function (obj) { return obj.images; }, set: function (obj, value) { obj.images = value; } }, metadata: _metadata }, _images_initializers, _images_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Product = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Product = _classThis;
}();
exports.Product = Product;
